name: tumorheal
description: TumorHeal Flutter frontend (scaffold with real payment SDK integration placeholders)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  json_annotation: ^4.9.0
  dio: ^5.3.2
  flutter_riverpod: ^2.4.4
  infinite_scroll_pagination: ^4.0.0
  equatable: ^2.0.5
  flutter_stripe: ^9.4.0
  pay: ^1.1.2
  crypto: ^3.0.3
  local_auth: ^2.1.6
  image_picker: ^0.8.7+4
  fl_chart: ^1.1.1
  url_launcher: ^6.1.12
  qr_flutter: ^4.1.0
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Firebase
  firebase_core: ^2.17.0
  firebase_analytics: ^10.5.1
  firebase_crashlytics: ^3.3.7
  
  # Network
  connectivity_plus: ^5.0.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  mockito: ^5.4.2


